Repository boothe0/CS386GodotProject, pull requests merged in 2025-03, with the labels that each got.

#118 interacting with shopkeeper now starts new round
  cs386gameproject/scenes/interactables/interacting_component.gd
  cs386gameproject/scenes/interactables/shopkeep.tscn
  cs386gameproject/scenes/main_scene.tscn
  cs386gameproject/scenes/shop_keeper.tscn
  cs386gameproject/scripts/shopkeep.gd
Labels: enhancement

#133 Projectile enemy
  cs386gameproject/assets/UI_Elements/04B_30__.TTF.import
  cs386gameproject/scenes/enemy_projectile.tscn
  cs386gameproject/scenes/main_scene.tscn
  cs386gameproject/scenes/ranged_enemy.tscn
  cs386gameproject/scenes/shop_scene.tscn
  cs386gameproject/scripts/enemy_projectile.gd
  cs386gameproject/scripts/player.gd
  cs386gameproject/scripts/ranged_enemy.gd
  cs386gameproject/scripts/shop/shop_display_item.gd
Labels: enhancement

#140 Refactored interaction system
  cs386gameproject/scenes/interactables/interactable.gd
  cs386gameproject/scenes/interactables/interactable.tscn
  cs386gameproject/scenes/interactables/interacting_component.gd
  cs386gameproject/scenes/interactables/interacting_component.tscn
  cs386gameproject/scenes/main_scene.tscn
  cs386gameproject/scenes/player.tscn
  cs386gameproject/scenes/shop_items/shop_item.tscn
  cs386gameproject/scenes/shop_scene.tscn
  cs386gameproject/scripts/player.gd
  cs386gameproject/scripts/shop/shop_display_item.gd
  cs386gameproject/scripts/shop/shop_interact.gd
  cs386gameproject/scripts/upgrades/player_variables.gd
Labels: bug, enhancement

#149 Try again button loads new game
  cs386gameproject/assets/UI_Elements/04B_30__.TTF.import
  cs386gameproject/assets/UI_Elements/death_theme.tres
  cs386gameproject/scenes/death.tscn
  cs386gameproject/scenes/main_scene.tscn
  cs386gameproject/scripts/death_scene.gd
Labels: enhancement

#148 Fixes item randomization to be truly random with weights
  cs386gameproject/scenes/interactables/shopkeep.tscn
  cs386gameproject/scenes/main_scene.tscn
  cs386gameproject/scenes/shop_items/consumables/rare/health_potion.json
  cs386gameproject/scenes/shop_items/consumables/uncommon/health_potion.json
  cs386gameproject/scenes/shop_items/shop_item.tscn
  cs386gameproject/scenes/shop_keeper.tscn
  cs386gameproject/scenes/shop_scene.gd
  cs386gameproject/scenes/shop_scene.tscn
  cs386gameproject/scripts/shop/shop_display_item.gd
Labels: bug

#153 Adds purchasable upgrades
  cs386gameproject/assets/UI_Elements/04B_30__.TTF.import
  cs386gameproject/assets/items/upgrades/breath.png
  cs386gameproject/assets/items/upgrades/breath.png.import
  cs386gameproject/project.godot
  cs386gameproject/scenes/consumables/heal_potion.tscn
  cs386gameproject/scenes/main_scene.tscn
  cs386gameproject/scenes/player_ui.gd.uid
  cs386gameproject/scenes/shop_items/consumables/common/health_potion.json
  cs386gameproject/scenes/shop_items/consumables/legendary/wall_potion.json
  cs386gameproject/scenes/shop_items/consumables/rare/health_potion.json
  cs386gameproject/scenes/shop_items/consumables/uncommon/health_potion.json
  cs386gameproject/scenes/shop_items/shop_item.tscn
  cs386gameproject/scenes/shop_items/upgrades/common/breath.json
  cs386gameproject/scenes/shop_items/upgrades/legendary/breath.json
  cs386gameproject/scenes/shop_items/upgrades/rare/breath.json
  cs386gameproject/scenes/shop_items/upgrades/uncommon/breath.json
  cs386gameproject/scripts/coins_text_death.gd.uid
  cs386gameproject/scripts/shop/shop_display_item.gd
  cs386gameproject/scripts/tutorial.gd.uid
  cs386gameproject/scripts/tutorial_player.gd.uid
  cs386gameproject/scripts/upgrades/breath.gd
  cs386gameproject/scripts/upgrades/breath.gd.uid
Labels: enhancement
